# Generated by Django 6.0.3 on 2026-03-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazakhfood', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('people_count', models.IntegerField(choices=[(1, '1 человек'), (2, '2 человека'), (3, '3 человека'), (4, '4 человека'), (5, '5+ человек')], verbose_name='Количество людей')),
            ],
        ),
    ]
